# Generated by Django 4.1.6 on 2023-03-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_status_type_remove_task_ended_at_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='webapp.status', verbose_name='Статус'),
        ),
    ]
