# Generated by Django 4.1.6 on 2023-03-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_project_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
