# Generated by Django 4.1.6 on 2023-03-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип задачи'},
        ),
    ]
