# Generated by Django 4.1.6 on 2023-04-17 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')], verbose_name='Заголовок'),
        ),
    ]
